### ISSUE TITLE
Duplication of Move Storage context menu item when connecting between multiple daemons.

### ISSUE THREAD

**Issue by Blazein** [dredkin/deluge-rbb#17]
I'm running v1.3.12 on all systems, my windows gtk client, local and hosted linux based seedboxes.

When the Browse Button plugin is enabled on all systems, the Move Storage item in a torrent's context menu gets duplicated each time I use the the connection manager to switch between different deluge hosts. This results in the Move Sorage item appearing in the context menu over 8 times in my testing.

See it: http://imgur.com/SnQk5UJ

With the plugin disabled, this issue does not occur. But, then I do not have a browse button :(

**Comment by Mattie432** [comment]
Likely an issue with the [addMoveButton](https://github.com/dredkin/deluge-rbb/blob/master/browsebutton/gtkui.py) implementation. Feel free to submit a fix, unsure when I can look into this.

**Comment by free8bit** [comment]
Same issue and I only have one deamon

**Comment by Mattie432** [comment]
Unsure, could look into [running in debug mode](http://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging) to see if any errors are output. Would give you a clearer idea of whats the problem.

**Comment by free8bit** [comment]
When I try to enable the plugin I get an error:

> [ERROR   ] 22:53:30 client:391 RPCError Message Received!
> --------------------------------------------------------------------------------
> RPCRequest: core.enable_plugin(browsebutton)
> --------------------------------------------------------------------------------
>   File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 299, in dispatch
>     ret = self.factory.methods[method](*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/deluge/core/core.py", line 524, in enable_plugin
>     self.pluginmanager.enable_plugin(plugin)
>   File "/usr/lib/python2.7/dist-packages/deluge/core/pluginmanager.py", line 82, in enable_plugin
>     super(PluginManager, self).enable_plugin(name)
>   File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 151, in enable_plugin
>     component.start([instance.plugin._component_name])
>   File "/usr/lib/python2.7/dist-packages/deluge/component.py", line 290, in start
>     if self.components[name]._component_depend:
> 
> KeyError: CorePlugin.browsebutton
> --------------------------------------------------------------------------------
> Unhandled error in Deferred:
> 
> 
> Traceback (most recent call last):
> Failure: deluge.ui.client.DelugeRPCError: <deluge.ui.client.DelugeRPCError object at 0x045F8150>

**Comment by Mattie432** [comment]
Are you running this through a py-egg you've built? Looks like the issue described [here](https://github.com/dredkin/deluge-rbb#windows)

**Comment by free8bit** [comment]
No I didn't built it myself. I'm using the py-egg you provided.

But I fixed the problem. I extracted the content from the py-egg into /usr/lib/python2.7/dist-packages/deluge/plugins/browserbutton/, then restarted and now it's working again.

Looks like that plug-in was deleted from the Server, but not from the list in the Client when I disable it.

**Comment by broizter** [comment]
Just wanted to chime in and say that I got the same problem while only running one daemon.

**Comment by dredkin** [comment]
I finally have some time to play with the code, so if you still want to fix the issue, I'd like to see the description and log files (don't forget to install the latest version from releases).

**Comment by beerandt** [comment]
I've got 4 different daemons from the same client- I've got the same problem, but can add a few details.

When the plug-in has been installed on only one daemon, it acts as if it's installed in all of them, except the browse box never populates with anything.

If you try this, then try to actually install the plug-in, the client freezes when you attempt to click the check box to activate the plug-in, without it getting checked. The only thing you can do is cancel out of the settings box.

If you return to settings, the plug-in is still not activated (box not checked). However, an additional menu item still gets added as described by others.

If you then activate the plug-in successfully, you get another copy of the line.

Right now, I've got 5 copies of the same line, having installed the plug-in on 3 of 4 daemons.

**Comment by dredkin** [comment]
please try this debug version.
https://yadi.sk/d/rO2R0DtByrkslw

**Comment by dredkin** [comment]
Please Restart deluge client after installing new version.

**Comment by dredkin** [comment]
This version does not address issues with plugin installation, it only should remove redundant items from context menu.

**Comment by dredkin** [comment]
> When the plug-in has been installed on only one daemon, it acts as if it's installed in all of them, except the browse box never populates with anything.

Totally expected, though I could add a message like "plugin not installed on server side"

> If you try this, then try to actually install the plug-in, the client freezes when you attempt to click the check box to activate the plug-in, without it getting checked. The only thing you can do is cancel out of the settings box.

This is a known issue, I didn't fix it yet. To install plugin correctly to server, you should manually copy it to daemon's plugins folder. It is mentioned in the Readme BTW.

> if you then activate the plug-in successfully, you get another copy of the line.

> Right now, I've got 5 copies of the same line, having installed the plug-in on 3 of 4 daemons.

This is is the issue I'm trying to fix. If it is fixed, I'll try to sort out thing with server-side installation.

**Comment by beerandt** [comment]
I finally got a chance to test it- the initial duplication sense to be
fixed. Before restarting, It appears as if it deleted the original "move
storage" line and appends a new one in the end of the context menu. After a
restart the item is back where it normally is.

I also installed it on a second daemon (right after the first one) just to
see. (Also, I didn't read the last reply until I was in the process.)

I got a brief pause when checking the box then clicking ok to activate the
plug-in, but it didn't freeze like before. It was successful on the first
attempt (paused, but didn't freeze, in the same way second attempts
previously were successful.)

As expected ( I think) the initial duplication is resolved, but there is
still a new duplicate every time I switched between daemons. Is this still
the known issue you described re: installing the egg instead of dropping it
in the folder?

I'm doing this via remote desktop, so I haven't gotten around to manually
dropping the egg in the other folders yet. But- since I installed it on 2
daemons already, how do I uninstall it from one? (Or both, if needed?) Just
manually delete the egg and rescan for plugins? Should that suffice?
