### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by meklon** [dredkin/deluge-rbb#19]
Nothing happens when checking plugin active after installation. OS: KDE Neon. Deluge is used as a remote to deluged. Terminal error output:
```bash
[ERROR   ] 22:00:15 client:391 RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.enable_plugin(browsebutton)
--------------------------------------------------------------------------------
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/deluge/core/core.py", line 540, in enable_plugin
    self.pluginmanager.enable_plugin(plugin)
  File "/usr/lib/python2.7/dist-packages/deluge/core/pluginmanager.py", line 82, in enable_plugin
    super(PluginManager, self).enable_plugin(name)
  File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 151, in enable_plugin
    component.start([instance.plugin._component_name])
  File "/usr/lib/python2.7/dist-packages/deluge/component.py", line 290, in start
    if self.components[name]._component_depend:

KeyError: CorePlugin.browsebutton
--------------------------------------------------------------------------------
Unhandled error in Deferred:


Traceback (most recent call last):
Failure: deluge.ui.client.DelugeRPCError: <deluge.ui.client.DelugeRPCError object at 0x7f6e3e042d10>
```

**Comment by meklon** [comment]
Problem was solved after several server-side deluged.service restarts.
