### ISSUE TITLE
Can't traverse into a directory with local characters

### ISSUE THREAD

**Issue by returnedinformation** [dredkin/deluge-rbb#20]
I can't traverse into directories which contains character č (and possibly other character like ćžšđ).. These are croatian local characters.. By trying to double click onto the folder nothing happens
Using deluged 1.3.15 on Ubuntu 18.04, libtorrent 1.1.13 as daemon, python 2.7
Using Deluge 1.3.15 on Windows 10, browsebutton 0.1.10 as client

**Comment by dredkin** [comment]
This is rather strange, because
1. Python fully supports Unicode
2. I always can traverse to folders containing Russian symbols, which are also non-Latin.

**Comment by dredkin** [comment]
I've just created a folder "č ćžšđ" and it opens correctly. I suggest there are some localization issues on your server.
What is the output of your `locale` command?

**Comment by returnedinformation** [comment]
I'm sorry I thought it had to do something with your plugin, but I don't know who to turn to.
This is my locale output
~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=hr_HR.UTF-8
LC_TIME=hr_HR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=hr_HR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=hr_HR.UTF-8
LC_NAME=hr_HR.UTF-8
LC_ADDRESS=hr_HR.UTF-8
LC_TELEPHONE=hr_HR.UTF-8
LC_MEASUREMENT=hr_HR.UTF-8
LC_IDENTIFICATION=hr_HR.UTF-8
LC_ALL=

thanks for such a quick response!

**Comment by dredkin** [comment]
Seems legit.
Also please check folder permissions for a deluge server user.

**Comment by returnedinformation** [comment]
I have checked,they arent different from any of the hunders of other folders I traverse into easily
I also cant traverse into any folders containing japanese characters
Im not much of a linux user so keep that in mind as well, the server might be misconfigured,I could try it on another ubuntu 18.04 machine and check

**Comment by dredkin** [comment]
Rbb supports deluge's logging.
1. run deluged with log level `debug` as descrired [here](https://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging)
2. reproduce the issue
3. look at the logfile, filter by "RBB:" keyword...

**Comment by returnedinformation** [comment]
```
[DEBUG   ] 14:46:20 core:118 RBB: config assigned
[DEBUG   ] 14:46:26 core:133 RBB:native folder/HDD/mininova
[DEBUG   ] 14:46:26 core:134 RBB:orig subfolder
[DEBUG   ] 14:46:30 core:133 RBB:native folder/HDD/mininova
[DEBUG   ] 14:46:30 core:134 RBB:orig subfolderMyAnonamouse
[DEBUG   ] 14:46:31 core:133 RBB:native folder/HDD/mininova/MyAnonamouse
[DEBUG   ] 14:46:31 core:134 RBB:orig subfolderLiteratura
[DEBUG   ] 14:46:32 core:133 RBB:native folder/HDD/mininova/MyAnonamouse/Literatura
[DEBUG   ] 14:46:32 core:134 RBB:orig subfolderPriručnici
[ERROR   ] 14:46:32 rpcserver:306 Exception calling RPC request: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/home/deluge/.config/deluge/plugins/browsebutton-0.1.10-py2.7.egg/browsebutton/core.py", line 135, in get_folder_list
    subfolder = subfolder.encode(CURRENT_LOCALE)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
[DEBUG   ] 14:46:33 core:133 RBB:native folder/HDD/mininova/MyAnonamouse/Literatura
[DEBUG   ] 14:46:33 core:134 RBB:orig subfolderPriručnici
[ERROR   ] 14:46:33 rpcserver:306 Exception calling RPC request: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/home/deluge/.config/deluge/plugins/browsebutton-0.1.10-py2.7.egg/browsebutton/core.py", line 135, in get_folder_list
    subfolder = subfolder.encode(CURRENT_LOCALE)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
[DEBUG   ] 14:46:50 core:118 RBB: config assigned
[DEBUG   ] 14:46:50 core:118 RBB: config assigned
```

I hope I've got everything you need, the issue seems to be logged

**Comment by dredkin** [comment]
Please test this version and report results.
https://yadi.sk/d/6XiVL8AmICCD3w

**Comment by returnedinformation** [comment]
```
$ deluged
$ [ERROR   ] 17:51:04 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 17:51:04 pluginmanagerbase:147 expected an indented block (core.py, line 140)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 144, in enable_plugin
    instance = cls(plugin_name.replace("-", "_"))
  File "/home/deluge/.config/deluge/plugins/browsebutton-0.1.11-py2.7.egg/browsebutton/__init__.py", line 44, in __i                                                      nit__
    from core import Core as _plugin_cls
  File "/home/deluge/.config/deluge/plugins/browsebutton-0.1.11-py2.7.egg/browsebutton/core.py", line 140
    if isinstance(subfolder, str):
     ^
IndentationError: expected an indented block

```

**Comment by dredkin** [comment]
https://yadi.sk/d/Vo9aPNuB8lA1gQ

**Comment by returnedinformation** [comment]
```
[DEBUG   ] 18:07:18 core:128 RBB:CURRENT_LOCALE is UTF-8
[DEBUG   ] 18:07:18 core:130 RBB:native folder=/HDD/mininova
[DEBUG   ] 18:07:18 core:131 RBB:orig subfolder=MyAnonamouse
[DEBUG   ] 18:07:18 core:134 RBB:folder decoded=/HDD/mininova
[DEBUG   ] 18:07:18 core:141 RBB:subfolder decoded=MyAnonamouse
[DEBUG   ] 18:07:19 core:128 RBB:CURRENT_LOCALE is UTF-8
[DEBUG   ] 18:07:19 core:130 RBB:native folder=/HDD/mininova/MyAnonamouse
[DEBUG   ] 18:07:19 core:131 RBB:orig subfolder=Literatura
[DEBUG   ] 18:07:19 core:134 RBB:folder decoded=/HDD/mininova/MyAnonamouse
[DEBUG   ] 18:07:19 core:141 RBB:subfolder decoded=Literatura
[DEBUG   ] 18:07:19 core:128 RBB:CURRENT_LOCALE is UTF-8
[DEBUG   ] 18:07:19 core:130 RBB:native folder=/HDD/mininova/MyAnonamouse/Literatura
[DEBUG   ] 18:07:19 core:131 RBB:orig subfolder=Priručnici
[DEBUG   ] 18:07:19 core:134 RBB:folder decoded=/HDD/mininova/MyAnonamouse/Literatura
[ERROR   ] 18:07:19 rpcserver:306 Exception calling RPC request: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/home/deluge/.config/deluge/plugins/browsebutton-0.1.11-py2.7.egg/browsebutton/core.py", line 140, in get_folder_list
    subfolder = subfolder.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
```
I'll be away for the next 2 hours

**Comment by dredkin** [comment]
https://yadi.sk/d/HFX5CWkmHhZ9Gw

**Comment by returnedinformation** [comment]
```
> [DEBUG   ] 20:23:50 core:128 RBB:CURRENT_LOCALE is UTF-8
> [DEBUG   ] 20:23:50 core:130 RBB:native folder=/HDD/mininova/MyAnonamouse/Literatura
> [DEBUG   ] 20:23:50 core:131 RBB:orig subfolder=Priručnici
```
There are no errors now anymore and it works properly! Thank you very much, I'm glad it could have been fixed!

**Comment by dredkin** [comment]
Could you please check that the released version still works? Thank you!

**Comment by returnedinformation** [comment]
everything seems to work well with the released version! I'm organizing torrents in deluge and moving data around a lot so I'll test it well. I'll report if anything seems out of order
