### ISSUE TITLE
Install error when I try to install the 2.7 egg on Deluge 1.3.15

### ISSUE THREAD

**Issue by jonesnc** [dredkin/deluge-rbb#23]
I get this error when I try to install the 2.7 egg on Deluge 1.3.15:

```
[ERROR   ] 05:19:29 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 05:19:29 pluginmanagerbase:147 u'deluge_browsebutton/data/browse_button.js.glade'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/pluginmanagerbase.py", line 144, in enable_plugin
    instance = cls(plugin_name.replace("-", "_"))
  File "build/bdist.linux-x86_64/egg/deluge_browsebutton/__init__.py", line 58, in __init__
    from .webui import WebUI as _plugin_cls
  File "build/bdist.linux-x86_64/egg/deluge_browsebutton/webui.py", line 47, in <module>
  File "build/bdist.linux-x86_64/egg/deluge_browsebutton/webui.py", line 49, in WebUI
  File "build/bdist.linux-x86_64/egg/deluge_browsebutton/common.py", line 23, in get_resource
    return resource_filename(__package__, os.path.join('data', filename + ext))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1145, in resource_filename
    self, resource_name
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1744, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1765, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: u'deluge_browsebutton/data/browse_button.js.glade'
```

I've tried doing the server restart that the README suggests, but to no avail. I've also tried building the egg myself for python 2.7 (which is what I'm running), but that also didn't fix the issue.

**Comment by dredkin** [comment]
Ok, I've seen the problem.

**Comment by dredkin** [comment]
please check a quickfix version:
https://yadi.sk/d/WMreoIUf6mCRrA

**Comment by jonesnc** [comment]
I tried it, and I didn't get the error and I was able to enable the plugin.

However, I'm not seeing the Browse button anywhere that it should be added.

**Comment by dredkin** [comment]
please collect logs from *client* in "debug" mode as it mentioned in [docs](https://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging).

**Comment by dredkin** [comment]
First of all, and it is mentioned in the docs: plugin DOES NOT support webui yet.
It is in plans, but not implemented.

**Comment by dredkin** [comment]
May I suggest you to Use gtk client to access your server?

**Comment by jonesnc** [comment]
Ohh, my mistake! I'm using Deluge on a seedbox, so I'm not sure I can run the gtk client to access my server.

**Comment by dredkin** [comment]
> 
> Ohh, my mistake! I'm using Deluge on a seedbox, so I'm not sure I can run the gtk client to access my server.
> 

Can't see any issue if you can open (or forward) ports on your seedbox. GTK client is much more convenient than web client and have higher plugins support.
